### ISSUE TITLE
Adress more than one CardDAV-Server

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#1]
It should be possible to address more than one CardDAV server. Conversion to one's own or mapping into a common phone book would be desirable as an option.

**Comment by andig** [comment]
> It should be possible to address more than one CardDAV server.

Lässt sich über einzelne Konfigurationsdateien lösen, baue ich ein.

> Conversion to one's own or mapping into a common phone book would be desirable as an option.

Anderes Thema. Bitte konkretes neues Issue aufmachen.

**Comment by andig** [comment]
Fixed via afdd8a0ab39e144e4a3445a204ae1d20c71c2ff4

**Comment by BlackSenator** [comment]
config.php still provides just one possibility to adress a CardDAV-Server

**Comment by andig** [comment]
Einfach 2. config nehmen
