### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#10]
Test with recent version:

Downloaded 1414 vcards
Converted 16 vcards
PHP Fatal error:  Uncaught Error: Call to undefined function Andig\load() in /carddav2fb/src/RunCommand.php:51
Stack trace:
#0 /carddav2fb/vendor/symfony/console/Command/Command.php(240): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /carddav2fb/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /carddav2fb/vendor/symfony/console/Application.php(216): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /carddav2fb/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /carddav2fb/carddav2fb.php(19): Symfony\Compone in /carddav2fb/src/RunCommand.php on line 51

Excerpt from config.php:

'excludes' => [
		'category' => [
			'dummy'
		],
		'group' => [
			'Business', 'Sonstige'
		],
	],

	'conversions' => [
		'vip' => [
			'category' => [
				'dummy'
			],
			'group' => [
				'VIP'
			],
		],
		'realName' => [
			'{lastname}, {firstname}',
			'{fullname}',
			'{organization}'
		],
		'phoneTypes' => [
			'WORK'   => 'work',
            'MAIN'   => 'work',		
			'HOME'   => 'home', 
			'CELL'   => 'mobile',
			'IPHONE' => 'mobile',
			'FAX'    => 'fax_work',
			'OTHER'  => 'sonstige',
			'PAGER'  => 'sonstige'
		],
		'emailTypes' => [
			'WORK' => 'work', 
			'HOME' => 'home'
		],

**Comment by BlackSenator** [comment]
The download command provides:

...
UID:FDEAB33B-5F5E-4D9F-9AD0-42E15728DD58&#13;
END:VCARD&#13;
</vcard>
 </element>
 <element>
  <id>RkU2NEYyRDQtODY5Mi00MzhGLUE3NTYtRkU2QzI1MTRGMkQz</id>
  <etag>C=8645@U=fcff104d-dd7e-4e46-9993-af63959f6b64</etag>
  <last_modified>Mon, 26 Jun 2017 14:38:06 GMT</last_modified>
  <vcard>BEGIN:VCARD&#13;
VERSION:3.0&#13;
PRODID:-//Apple Inc.//iOS 10.3.2//EN&#13;
...

**Comment by andig** [comment]
Fixed via aa6b430cf8a65880f52c00ea6bde2a733c9d8778

> The download command provides:

Wrong issue?
