### ISSUE TITLE
Tracking issue: refactoring errors

### ISSUE THREAD

**Issue by derwok** [andig/carddav2fb#107]
I'm testing the current master commit 9cbc1b87f984a49b3f391393d5b804e66c132e77
This version crashes with the following exception on a `run -i`:
``` 
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Andig\CardDav\Backend::embedBase64() must be of the type array, object given, called in /home/pi/bin/carddav2fb/src/CardDav/Backend.php on line 196 and defined in /home/pi/bin/carddav2fb/src/CardDav/Backend.php:117
Stack trace:
#0 /home/pi/bin/carddav2fb/src/CardDav/Backend.php(196): Andig\CardDav\Backend->embedBase64(Object(stdClass), 'photo', 'https://www.wok...')
#1 /home/pi/bin/carddav2fb/src/CardDav/Backend.php(225): Andig\CardDav\Backend->getVcard('6105BB55-14F6-4...')
#2 /home/pi/bin/carddav2fb/src/CardDav/Backend.php(105): Andig\CardDav\Backend->processPropFindResponse(Object(SimpleXMLElement))
#3 /home/pi/bin/carddav2fb/src/functions.php(41): Andig\CardDav\Backend->getVcards()
#4 /home/pi/bin/carddav2fb/src/RunCommand.php(51): Andig\download(Object(Andig\CardDav\Backend), Array, Object(Closure))
#5 /home/pi/bin/carddav2fb/vendor/symfony/console/Command/Command.php(255): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony in /home/pi/bin/carddav2fb/src/CardDav/Backend.php on line 117
``` 
I could track down the problem to exactly this commit:
8e74117ac2aabe06bf2e4ca09112a3cbf5667b5d - this introduced the above error.
One commit prior this one all runs fine.
I assume the error was introduced in file `src/CardDav/Backend.php` in line 117.
https://github.com/andig/carddav2fb/blob/8e74117ac2aabe06bf2e4ca09112a3cbf5667b5d/src/CardDav/Backend.php#L117

But I fear my PHP knowledge is to small to provide a fix.

@andig: Could you please take over?

**Comment by derwok** [comment]
Ah - sorry I was not 100% precise:
The current master has an exception on exactly this line. But the error code is slightly different:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Andig\CardDav\Backend::embedBase64() must be an instance of Andig\CardDav\object, instance of stdClass given, called in /home/pi/bin/carddav2fb/src/CardDav/Backend.php on line 201 and defined in /home/pi/bin/carddav2fb/src/CardDav/Backend.php:117
Stack trace:
#0 /home/pi/bin/carddav2fb/src/CardDav/Backend.php(201): Andig\CardDav\Backend->embedBase64(Object(stdClass), 'photo', 'https://www.wok...')
#1 /home/pi/bin/carddav2fb/src/CardDav/Backend.php(230): Andig\CardDav\Backend->getVcard('68609498-7e94-4...')
#2 /home/pi/bin/carddav2fb/src/CardDav/Backend.php(105): Andig\CardDav\Backend->processPropFindResponse(Object(SimpleXMLElement))
#3 /home/pi/bin/carddav2fb/src/functions.php(41): Andig\CardDav\Backend->getVcards()
#4 /home/pi/bin/carddav2fb/src/RunCommand.php(47): Andig\download(Object(Andig\CardDav\Backend), Array, Object(Closure))
#5 /home/pi/bin/carddav2fb/vendor/symfony/console/Command/Command.php(255): Andig\RunCommand->execute(Object(Symfony\Component\Console\ in /home/pi/bin/carddav2fb/src/CardDav/Backend.php on line 117
```

The latest commit I see on master is: 9cbc1b87f984a49b3f391393d5b804e66c132e77
And this commit has the error in my comment here.
Sorry for confusion.

The line 117 makes proplems either as `must be of the type array, object given` or as `must be an instance of Andig\CardDav\object, instance of stdClass given` no version currently works.

**Comment by andig** [comment]
Pushed another one. Problem was that `object` should have been `\object` from global namespace.

**Comment by derwok** [comment]
OK! Great! Thx - crash is gone. That was fast!  
:-)

But now I see hundreds of these warnings (actually with every vCard parsed one):
```
PHP Warning:  property_exists() expects parameter 2 to be string, object given in /home/pi/bin/carddav2fb/src/CardDav/Backend.php on line 119
```
=> shall we close this issue and create a new issue for the above warning?

**Comment by andig** [comment]
Fixed. Its so hard to squash validation errors in a grown codebase without introducing new bugs. But it will make error checking simpler going forward.

**Comment by derwok** [comment]
Hey @andig,
now the described errors and warnings are gone. 
We may close this issue
Many thanx!

Unfortunately uploading the phonebook to FB now does not work any more...
I'll open a separate ticket with details.
