### ISSUE TITLE
rtrim in getvcard cripples the ID

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#112]
The rtrim command in Backend.php cripples the vCard ID (in some cases?)

Here is a quick output from echos befor and after line 193:

```
...
1836ACFE-3416-485B-80BC-0BEF469D8FBD.vcf
   26 [-------------------------->-]18737d82-d14e-437b-a380-597fca0ecf09 .vcf
18737d82-d14e-437b-a380-597fca0ecf09.vcf
   27 [--------------------------->]189efc8f-8294-45be-9d39-be0994410b1c .vcf
189efc8f-8294-45be-9d39-be0994410b1.vcf

In RequestException.php line 113:

  Client error: `GET https://p27-contacts.icloud.com/1019761670/carddavhome/card/189efc8f-8294-45be-9d39-be0994410b1.vcf` resulted in a `404 Not Found` response:
  Not Found

```
As you can see: in #27 the last char "c" vanished.
What´s the reason for this line?
`$id = rtrim($vcard_id, $this->vcard_extension) . $this->vcard_extension;`
First trim right and than append the same string - doesn´t make sense to me.

**Comment by BlackSenator** [comment]
The 30fab4f9696378c7eac4f439f87e721ae21e784c is safe

**Comment by andig** [comment]
Ist behoben
