### ISSUE TITLE
Feature Request: Include filter for contacts

### ISSUE THREAD

**Issue by MarkusHLudwigsfeld** [andig/carddav2fb#13]
Hi,

I just tried this script and I like it very much :-)
I use Nextcloud on my Synology and push the address book to my FritzBox.

Since I have a lot of Contacts > 1000 and I am using VCARD Categories to organize them.
I have a Category "FritzBox" which has about 150 Contacts and those I want to have on my FritzBox, the others not.

Now I created an seperate accout on the Nextcloud and copied FritzBox Contacts to to a seperate address book.

However a cool feature I wish to have that I can enable an optional filter for Categories of my Contacts.

(I have a wish, because it's x-mas time ;-) )

**Comment by BlackSenator** [comment]
Hi Andreas,

that´s what I´ve foreseen, wehen I wrote in issue #9:

"2. Definition of CATEGORIES (1..n) which should explicit not be uploaded to FB. **To give the user more flexibility this could be combined in addition with an boolean flag if this configuration of categories should excluded (default) or included**."

**Comment by andig** [comment]
> However a cool feature I wish to have that I can enable an optional filter for Categories of my Contacts.

@MarkusHLudwigsfeld have you seen https://github.com/andig/carddav2fb/blob/master/config.example.php#L24? You can stick _any_ attribute of the vcard into the `excludes` and it will be matched. Only condition is that it needs to match exactly. 

If this doesn't work (untested) please should me a sample vcard and config. Deeply nested attributes are not supported (yet).

**Comment by MarkusHLudwigsfeld** [comment]
Hi andig, 

I have'n seen that there is a similar request, sorry.
I used latest version from BlackSenetor. 

However, it would be good to have an include filter because, I am using about 30 Categories and want to inculde only contacts which have the category "FritzBox". 
Those contacts have mostly other Categories as well.
This means excluding does not work for me.

E.g. a single contact might have the categories: FritzBox, School
or categories: FritzBox, Work

I would not like to have all people from Work in my FB.
And if I exclude Work, non will be the the FB. :-/


thanks,
Markus

**Comment by andig** [comment]
@MarkusHLudwigsfeld hast Du eine Vorstellung wie das bei konkurrierenden Filtern funktionieren soll, also z.B. wenn `exclude`und `include` spezifiziert sind? Ist `exclude` immer zu ignorieren wenn `include` gesetzt ist? Oder soll `include` final das `exclude` übersteuern?

**Comment by MarkusHLudwigsfeld** [comment]
Hallo Andig,

Gute Frage.
Ich denke das wichtigste ist, daß es am Ende gut dokumentiert ist.

Gibt es eine sinnvolle Anwendung beide Filter zu aktivieren?

Evtl könnte man erst den Include Filter anwenden und darauf wieder eine Teilmenge excludieren.
Wenn der include Filter leer ist werden alle selektiert und nur der exclude Filter angewendet.
Eigentlich sollten die gleichen Elemente rauskommen wenn man die Filter Reihenfolge umdreht.

Liste der Categoris enthält mindestens ein Element aus der Include Liste jedoch keines aus der Exclude Liste.

Schöne Grüße 
Markus 



Am 29. November 2017 13:54:55 OEZ schrieb andig <notifications@github.com>:
>@MarkusHLudwigsfeld hast Du eine Vorstellung wie das bei
>konkurrierenden Filtern funktionieren soll, also z.B. wenn `exclude`und
>`include` spezifiziert sind? Ist `exclude` immer zu ignorieren wenn
>`include` gesetzt ist? Oder soll `include` final das `exclude`
>übersteuern?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/andig/carddav2fb/issues/13#issuecomment-347838439

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by MarkusHLudwigsfeld** [comment]
@andig was denkst du über meinen Vorschlagn? 

Grüße Markus 


Am 29. November 2017 13:54:55 OEZ schrieb andig <notifications@github.com>:
>@MarkusHLudwigsfeld hast Du eine Vorstellung wie das bei
>konkurrierenden Filtern funktionieren soll, also z.B. wenn `exclude`und
>`include` spezifiziert sind? Ist `exclude` immer zu ignorieren wenn
>`include` gesetzt ist? Oder soll `include` final das `exclude`
>übersteuern?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/andig/carddav2fb/issues/13#issuecomment-347838439

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by andig** [comment]
> was denkst du über meinen Vorschlag?

Klingt vernünftig. Ich bin mir nicht sicher ob die Reihenfolge wirklich egal ist.

@BlackSenator wäre es ok wenn wir mit `include` als erstem Selektor starten, wenn nicht definiert dann "alle"?

**Comment by BlackSenator** [comment]
Hallo,

ich habe die Verwendung von include und exclude als OR immer noch nicht verstanden - aber als XOR ergibt das für mich einen Sinn.

Volker

**Comment by MarkusHLudwigsfeld** [comment]
@BlackSenator 
@andig 

Das ist ein logisches UND würde ich sagen...  Mit dem Sonderfall Include Liste leer...  Sieht das so aus...
Die Klammern sind zu beachten, sonst wird's falsch.

(
INCLUDE Liste ist leer 
ODER 
Mindestes eine Kategorie der VCARD ist in der INCLUDE Liste enthalten
)
UND 
Keine Kategorie der VCARD ist in der EXCLUDE Liste. 


Grüße Markus 




Am 4. Dezember 2017 13:04:26 OEZ schrieb Black Senator <notifications@github.com>:
>Hallo,
>
>ich habe die Verwendung von include und exclude als OR immer noch nicht
>verstanden - aber als XOR ergibt das für mich einen Sinn.
>
>Volker
>
>
>> Am 04.12.2017 um 11:46 schrieb andig <notifications@github.com>:
>> 
>> was denkst du über meinen Vorschlag?
>> 
>> Klingt vernünftig. Ich bin mir nicht sicher ob die Reihenfolge
>wirklich egal ist.
>> 
>> @BlackSenator wäre es ok wenn wir mit include als erstem Selektor
>starten, wenn nicht definiert dann "alle"?
>> 
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/andig/carddav2fb/issues/13#issuecomment-348930083

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by BlackSenator** [comment]
Sorry,

ergibt für mich immer noch keinen Sinn:

Ausgang:
Der User hat n vCards welche mehr oder weniger vollständig  kategorisiert/gruppiert sind.
Entweder ist es einfacher für ihn die Kategorien/Gruppen zu definieren welche excludiert werden sollen oder (XOR) zu definieren welche ausschließlich übernommen (includiert) werden sollen.

Ein UND beider Abfragen auf die Grundgesamtheit ergibt für mich keinen Sinn!
Keep it simple and stupid!

Volker

**Comment by andig** [comment]
> ergibt für mich immer noch keinen Sinn

Kommt auf den Anwendungsfall drauf an bzw. womit man sich leichter tut. 1 include ist einfacher als 10 excludes. 

Ich verstehe den Widerstand nicht- es tut doch auch nicht weh?

**Comment by MarkusHLudwigsfeld** [comment]
@BlackSenator, @andig 
Hallo Volker, 

mir scheint wir haben noch ein unterschiedliches Verständnis von der Sache. 
Mir ist unklar, wo Du das "Exclusiv Oder" siehst?
Meinst Du damit, dass nur der Include oder der Exclude Filter aktiv sein sollte??
-> Das ergibt sich automatisch wenn nur eine Liste Elemente enthält.

Das Benutzer sollte sich überlegen, was passiert wenn er beide Listen definiert. 
Das kann Sinnvoll sein, natürlich kann man damit auch blödsinn machen, wenn beide Listen die gleiche Kategorie entahlten, aber ich meine so viel Intelligenz sollte man einem Anwender zutrauen.


Ich sehe folgende Szenarien: (Logik wie oben definiert.)

VCARD1_CAT="Arbeit"
VCARD2_CAT="Freunde, Arbeit"
VCARD3_CAT="Freunde, Nachbarn"
VCARD4_CAT="Nachbarn"
VCARD5_CAT="Familie"
VCARD6_CAT="Schule"
VCARD7_CAT="Schule, Freunde"
VCARD8_CAT="Studium"
VCARD9_CAT="Studium, Freunde"



1)
INCLUDE="Freunde, Familie, Nachbarn"
EXCLUDE=""

Hier ist nur der Include Filter wirksam, da die Exclude Liste Leer ist, folgende werden ausgewählt:
VCARD2_CAT="Freunde, Arbeit"
VCARD3_CAT="Freunde, Nachbarn"
VCARD4_CAT="Nachbarn"
VCARD5_CAT="Familie"
VCARD7_CAT="Schule, Freunde"
VCARD9_CAT="Studium, Freunde"

2)
INCLUDE=""
EXCLUDE="Schule, Studium"

Hier ist nur der Exclude Filter wirksam, da die Include Liste Leer ist, folgende werden ausgewählt:
VCARD1_CAT="Arbeit"
VCARD2_CAT="Freunde, Arbeit"
VCARD3_CAT="Freunde, Nachbarn"
VCARD4_CAT="Nachbarn"
VCARD5_CAT="Familie"


3)
INCLUDE="Freunde, Familie"
EXCLUDE="Schule, Studium"

3.1.a) Include Liste abarbeiten:
VCARD2_CAT="Freunde, Arbeit"
VCARD3_CAT="Freunde, Nachbarn"
VCARD5_CAT="Familie"
VCARD7_CAT="Schule, Freunde"
VCARD9_CAT="Studium, Freunde"

3.1.b) Exlclude auf 3a) anwenden:  (Endergebnis)
VCARD2_CAT="Freunde, Arbeit"
VCARD3_CAT="Freunde, Nachbarn"
VCARD5_CAT="Familie"


Wenn die Filter Reihenfolge umgekehrt wird:

3.2.a) Erst Exclude anwenden:
VCARD1_CAT="Arbeit"
VCARD2_CAT="Freunde, Arbeit"
VCARD3_CAT="Freunde, Nachbarn"
VCARD4_CAT="Nachbarn"
VCARD5_CAT="Familie"

3.2.b) Dann Include anwenden auf 3.2.a):
VCARD2_CAT="Freunde, Arbeit"
VCARD3_CAT="Freunde, Nachbarn"
VCARD5_CAT="Familie"


Das Ergebnis ist das gleiche wie bei 3.1.b), sonst würde ja was mit der boolschen Algebra nicht stimmen ;-)

Grüße,
Markus

**Comment by andig** [comment]
Siehe https://github.com/andig/carddav2fb/commit/7f61b36c39c13d0b3a7081d93f5b9a90910778b4 bitte geänderte Konfiguration beachten. Ungetestet :O

**Comment by MarkusHLudwigsfeld** [comment]
Hallo,

es gibt in der VCARD "category" und "categories".
"category" kann nur einen Wert enthalten.
"categories" kann mehrere Werte enthalten.

In der Config muss ich also categories verwenden:
```
    'filters' => [
        'include' => [
            // if empty include all by default
         'categories' => [
                'FritzBox',
                ],
        ],
```


Da categories ein array ist, muss src/functions.php angepasst werden:


```
 function filterMatches($attribute, $filterValues): bool
 {
     if (!is_array($filterValues)) {
         $filterValues = array($filterMatches);
     }
 
     foreach ($filterValues as $filter) {
-        if ($attribute === $filter) {
-            return true;
+        if (is_array($attribute)) {
+        
+            foreach ($attribute as $currentAttribute) {
+                if ($currentAttribute === $filter) {
+                    error_log(sprintf("5a"));
+                    return true;
+                    }
+                }
+        } else {
+            if ($attribute === $filter) {
+                return true;
+            }
         }
     }
 
     return false;
 }
```


@andig 
Es scheint Du hast recht viel umgebaut, leider kommen die Fotos nicht mehr mit.
Fehlt das nur in der config?

**Comment by andig** [comment]
> Da categories ein array ist, muss src/functions.php angepasst werden:

Tatsächlich hatte ich Matching von arrays noch gar nicht implementiert, aber ok ;)

> Es scheint Du hast recht viel umgebaut, leider kommen die Fotos nicht mehr mit.

Ich denke das ging bei mir noch nie. Oder meinst Du den --image switch? Kann sein dass ich den beim `RunCommand` vergessen habe.

Echter Foto Upload ist noch in der Pipeline.

**Comment by andig** [comment]
Arrays sind implementiert: https://github.com/andig/carddav2fb/commit/0323aa57b607c65fa0b03901af411156440f814d

Können wir dieses Ticket zumachen?

**Comment by MarkusHLudwigsfeld** [comment]
denke ja
