### ISSUE TITLE
Still buggy

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#14]
Hallo Andreas,

I tested the new version - with both datasets (my own and Camerons) - both crashed:

Here are the result from Camerons contacts:

Downloaded 53 vcards
Converted 50 vcards
PHP Fatal error:  Uncaught Error: Call to undefined function Andig\upload() in /carddav2fb/src/RunCommand.php:51
Stack trace:
#0 /carddav2fb/vendor/symfony/console/Command/Command.php(240): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /carddav2fb/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /carddav2fb/vendor/symfony/console/Application.php(216): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /carddav2fb/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /carddav2fb/carddav2fb.php(19): Symfony\Compo in /carddav2fb/src/RunCommand.php on line 51

**Comment by BlackSenator** [comment]
and here are mine (looks the same):

Downloaded 1410 vcards
Converted 1392 vcards
PHP Fatal error:  Uncaught Error: Call to undefined function Andig\upload() in /carddav2fb/src/RunCommand.php:51
Stack trace:
#0 /carddav2fb/vendor/symfony/console/Command/Command.php(240): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /carddav2fb/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /carddav2fb/vendor/symfony/console/Application.php(216): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /carddav2fb/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /carddav2fb/carddav2fb.php(19): Symfony\Compo in /carddav2fb/src/RunCommand.php on line 51

**Comment by andig** [comment]
Fixed
