### ISSUE TITLE
Using config.cron container ends with "sleep: invalid number '4h'"

### ISSUE THREAD

**Issue by kremanjel** [andig/carddav2fb#148]
Using the config.cron file in data folder with following content:
INTERVAL=4h
RUN_OPTIONS=

Running the docker container it runs through with a successfull convertion but then ends with with following message:
sleep: invalid number '4h'

**Comment by andig** [comment]
cc @Skyr

**Comment by andig** [comment]
I'm closing this one as I cannot repro. The default 4h setting works fine for me when mounted into the container. Feel free to reopen with steps to reproduce.

**Comment by Skyr** [comment]
@kremanjel wild guess: Did you edit the config file on Windows? Then you probably have a file with Windows line endings (crlf), which causes strange errors in Linux shells.
