### ISSUE TITLE
Even worse...

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#15]
volumio@volumio:/$ git clone https://github.com/andig/carddav2fb.git
Cloning into 'carddav2fb'...
remote: Counting objects: 993, done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 993 (delta 112), reused 127 (delta 57), pack-reused 806
Receiving objects: 100% (993/993), 294.98 KiB | 160.00 KiB/s, done.
Resolving deltas: 100% (547/547), done.
Checking connectivity... done.
volumio@volumio:/$ cd carddav2fb
volumio@volumio:/carddav2fb$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.3.13): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing symfony/console (v3.3.13): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.0): Downloading (100%)
  - Installing ringcentral/psr7 (1.2.1): Downloading (100%)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/filesystem ()
symfony/console suggests installing symfony/process ()
Writing lock file
Generating autoload files
volumio@volumio:/carddav2fb$ php carddav2fb.php run
Downloading
    0 [>---------------------------]PHP Fatal error:  Uncaught Error: Call to undefined method Andig\CardDav\Backend::setAuth() in /carddav2fb/src/functions.php:14
Stack trace:
#0 /carddav2fb/src/RunCommand.php(38): Andig\download('https://p68-con...', 'cameron.howe@an...', 'njco-lpvq-udmg-...', Object(Closure))
#1 /carddav2fb/vendor/symfony/console/Command/Command.php(240): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /carddav2fb/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /carddav2fb/vendor/symfony/console/Application.php(216): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /carddav2fb/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Obj in /carddav2fb/src/functions.php on line 14

**Comment by andig** [comment]
Ups, da hab ich ein wenig heftig aufgeräumt. Behoben.

Und mach mal statt git clone einfach ein git pull um die letzten Änderungen zu bekommen- geht viel schneller...
