### ISSUE TITLE
another SSL download issue?

### ISSUE THREAD

**Issue by ragee-ra** [andig/carddav2fb#154]
Hi there!
I used to have an older version of carddav2fb running for many years
now. While setting up a new server I switched to the latest carddav2fb
version. Now I'm stuck with a download problem and and cannot figure
out what is going wrong. Any help is very much appreciated!

Here are the hard facts:
- connect to my carddav server via https://
- server has a self signed certificate
- in carddav2fb config.php I disabled certificate check ('verify' => false)

when calling 'php carddav2fb download -r test.json' I get the
following information:

$ php carddav2fb download -r test.json
Downloading vCard(s) from account ra
    0 [>---------------------------]*   Trying xx.xx.xx.xx...
* TCP_NODELAY set
* Connected to calendar.xxxxxxx.de (xx.xx.xx.xx) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / DHE-RSA-AES256-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=DE; ST=Bremen; L=Bremen; O=Internet Widgits Pty Ltd; CN=calendar.xxxxxxx.de; emailAddress=webmaster@xxxxxxx.de
*  start date: May  3 11:39:09 2018 GMT
*  expire date: May  2 11:39:09 2021 GMT
*  issuer: C=DE; ST=Bremen; L=Bremen; O=Internet Widgits Pty Ltd; CN=calendar.xxxxxxx.de; emailAddress=webmaster@xxxxxxx.de
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> REPORT /caldav.php/ra/privadr/ HTTP/1.1
Host: calendar.xxxxxxx.de
Depth: 1
User-Agent: GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.19-0ubuntu0.18.04.2
Authorization: Basic cmE6ZGxhLDYzcmVn
Content-Length: 239

* upload completely sent off: 239 out of 239 bytes
< HTTP/1.1 207 Multi-Status
< Date: Tue, 27 Aug 2019 07:24:03 GMT
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.26
< DAV: 1, 2, 3, access-control, calendar-access, calendar-schedule
< DAV: extended-mkcol, bind, addressbook, calendar-proxy
< ETag: "a6b28d2aee775f90e31b603f8f245096"
< X-DAViCal-Version: DAViCal/1.1.4; DB/1.3.3
< Content-Length: 25513438
< Content-Type: text/xml; charset="utf-8"
< 
* OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
* stopped the pause stream!
* Closing connection 0

In CurlFactory.php line 186:
                                                                                                                                      
  cURL error 56: OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0 (see htt  
  p://curl.haxx.se/libcurl/c/libcurl-errors.html)                                                                                     

Hope you can help....

**Comment by andig** [comment]
You'll need to report at the used guzzlehttp library or underlying curl. Seems encryption is not working.

**Comment by ragee-ra** [comment]
How can I do so?  Do you refer to the client side where the carddav2fb is running or the server side?

**Comment by andig** [comment]
Unfortunately I don't know. Sounds like an infrastructure issue- curl (or OS config) not working with webserver/ certificates.

**Comment by ragee-ra** [comment]
Ok. Thank you anyway...
