### ISSUE TITLE
CATEGORIES are not considered as exclude

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#17]
Testset cameron: vCARDs contain categories - analogous to the groups (PERS,ORGA,VIP)

config.php:
	'excludes' => [
		'category' => ['ORGA'	
		],
        'group' => [ 
		],
	],

Result:
Downloading
   53 [============================]
Downloaded 53 vcards
Converting
Converted 50 vcards

**Comment by andig** [comment]
User error- source includes `categories`, not `category`.
