### ISSUE TITLE
Allow URI as data for vcard PHOTO

### ISSUE THREAD

**Issue by SpamReceiver** [andig/carddav2fb#170]
Nextcloud has implemented a change to allow URI as data for VCards: https://github.com/nextcloud/server/pull/13117
Consequently, I find in my database a number of VCFs 3.0 with:
`BEGIN:VCARD`
`VERSION:3.0`
`PRODID:-//Sabre//Sabre VObject 4.1.6//EN`
`UID:C7821D49-BED0-0001-7F2A-E8507C67107F.vcf`
`FN:xxxx`
`ORG:xxxx`
`PHOTO;VALUE=URI:DATA:IMAGE/JPEG;BASE64\,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAA`

These photos are not recognized by carddav2fb und thus missing from the uploaded phonebook.

**Comment by blacksenator** [comment]
Okay
