### ISSUE TITLE
Alphatest?

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#18]
Testset:
cameron.howe

config.php:
'excludes' => [
'category' => [
],
'group' => ['ORGA'
],
],
'conversions' => [
		'vip' => [
			'category' => [
			],
			'group' => ['VIP'
			],
		],

Result:
Downloading
   53 [============================]
Downloaded 53 vcards
Converting
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Andig\filtersMatch() must be an instance of Andig\object, instance of stdClass given, called in /carddav2fb/src/functions.php on line 76 and defined in /carddav2fb/src/functions.php:86
Stack trace:
#0 /carddav2fb/src/functions.php(76): Andig\filtersMatch(Object(stdClass), Array)
#1 /carddav2fb/src/RunCommand.php(54): Andig\filter(Array, Array)
#2 /carddav2fb/vendor/symfony/console/Command/Command.php(240): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /carddav2fb/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /carddav2fb/vendor/symfony/console/Application.php(216): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Outp in /carddav2fb/src/functions.php on line 86

**Comment by andig** [comment]
Bitte testen. Ich hab gerade alles auf links gezogen um damit den Image Download vorzubereiten. Bei mir tuts im e2e test...

**Comment by andig** [comment]
Agh. Hab aus Versehen ein php7.2 feature benutzt was bei mir natürlich geht. Ist ausgebaut.
