### ISSUE TITLE
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by agolks** [andig/carddav2fb#185]
hi,

ich bleib mal bei deutsch.

ich versuche das ding auf raspbian 9 auf einem rpi4 zu installieren.
die pakete habe ich mit php7.3-* installiert, nur php-* ging nicht.
composer install --no-dev liefert mir aber einen fehler:
`Loading composer repositories with package information
Updating dependencies

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?`

ich schätze es liegt an php7.3?
gibts schon patches?
alternative möglichkeiten?

**Comment by agolks** [comment]
konnte zwar mit 7.1 installieren, aber ich will das system mit 7.3 als default laufen lassen...

**Comment by andig** [comment]
Aktuelle Composerversion?

Viele Grüße,
Andreas

**Comment by agolks** [comment]
Composer version 1.2.2 2016-11-03 17:43:15

**Comment by andig** [comment]
Then please update it 2016 is from the stone age.

**Comment by agolks** [comment]
oO
Crazy, i'll try. Nevertheless the build with 7.1. seems to work, too, with 7.3.
But i'll leave a note if updated composer will fix this issue, too.

**Comment by agolks** [comment]
works with current composer without any issues.
sorry for the noise ;)
