### ISSUE TITLE
Switch from REPORT to PROPFIND

### ISSUE THREAD

**Issue by develth** [andig/carddav2fb#188]
Hi

i found out that the sync didn´t worked for me anymore since the switch from `PROPFIND` to `REPORT`. 

Maybe we could easily switch back to `PROPFIND` with the following Setup:

`PROPFIND $url`
```
<d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:carddav">
  <d:prop>
     <c:address-data />
     <d:getetag />
  </d:prop>
</d:propfind>
```

The Result looks good:

```
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:a="urn:ietf:params:xml:ns:carddav" xmlns:D="DAV:">
    <D:response>
        <D:href>/SOGo/dav/mail@mail.de/Contacts/B1-5E170780-1-10AF9A80/B1-5E170780-3-10AF9A80.vcf</D:href>
        <D:propstat>
            <D:status>HTTP/1.1 200 OK</D:status>
            <D:prop>
                <a:address-data>BEGIN:VCARD
UID:B1-5E170780-3-10AF9A80.vcf
VERSION:3.0
CLASS:PUBLIC
PROFILE:VCARD
N:Test;Propfind
NICKNAME:Nick
FN:The Label Name
ORG:Supercorp
TEL;TYPE=home:100000001
END:VCARD</a:address-data>
                <D:getetag>&quot;gcs00000000&quot;</D:getetag>
            </D:prop>
        </D:propstat>
    </D:response>
</D:multistatus>
```

Could you please check if it works with your Servers, too?

| Server | PROPFIND | RESULT |
|--------|----------|--------|
| SOGo   |     ✅      |   ❌     |
|        |          |        |

Thanks & best regards
Thomas

**Comment by andig** [comment]
Could you please add a tracking table here or in the PR:

- which server REPORT works on or not (as far as we know)
- which server PROPFIND works on

Will PROPFIND still retrieve the entire result set in a single run instead of individual requests?

**Comment by develth** [comment]
> Will PROPFIND still retrieve the entire result set in a single run instead of individual requests?

Yes, it is included!

**Comment by develth** [comment]
Table is included in original Comment

**Comment by develth** [comment]
What Servers do you use? Then i could go for testing.

**Comment by andig** [comment]
Let us please restructure the problem:

- `PROPFIND` works fine- this is the old implementation, but it was horrible slow as it required one request per contact
- this issue suggests to switch back to `PROPFIND`, but plus `CARDDAV:address-data` to get everything in one request (@develth not sure why you'd need to etag, but that would help with intermediary caches?)
- for certain servers, `REPORT` works fine- this is the current implementation
- for some server, `REPORT` doesn't work without `CARDDAV:filter` - https://github.com/andig/carddav2fb/issues/167#issuecomment-575091400 shows how to add that filter
- for some servers, `REPORT` with `CARDDAV:filter` is broken, https://github.com/andig/carddav2fb/issues/167#issuecomment-575091400 demonstrates that on Synology. Imho that is a server issue and should not be worked around on our side.

So how to we proceed? I feel it's either:
- `REPORT` plus filter- sometimes broken
- `PROPFIND` plus `CARDDAV:address-data`

Does that make any sense? Opinions?

**Comment by andig** [comment]
@develth does `REPORT` work for your with filter as in https://github.com/andig/carddav2fb/issues/167#issuecomment-575091400?

**Comment by develth** [comment]
@andig nope and it just returns a (seems like) cached result. Regardless what i change inside it returns the same result

**Comment by andig** [comment]
Any chance to work around on the HTTP client side, e.g. no-cache, must-revalidate? Could be a proxy and not your carddav server that is the problem?

**Comment by develth** [comment]
Nothing worked, its a issue with REPORT

**Comment by develth** [comment]
```
Allow: GET, HEAD, POST, OPTIONS, MKCOL, MKCALENDAR, DELETE, PUT, LOCK, UNLOCK, COPY, MOVE, REPORT, PROPFIND, SEARCH
```

**Comment by andig** [comment]
It might make sense to support both `REPORT` and `PROPFIND`. Added a PR to allow that, fttb need to modify the code, will add config setting later if this works.

**Comment by matzesa** [comment]
Sounds good. I had problems with iCloud (500 Internal Server Error) and carddav2fb (Version 15.11.2018) so I updated yesterday. iCloud is working but now I have problems with Synology DiskStation (CardDav Server 6.0.9-0087; Workaround: https://github.com/andig/carddav2fb/issues/167#issuecomment-575091400).

**Comment by andig** [comment]
> Workaround: https://github.com/andig/carddav2fb/issues/167#issuecomment-575091400

That won't get merged. The Synology software is so severely broken in this case that it should be fixed. Opening an upstream ticket should help with that ;)
