### ISSUE TITLE
Exclude selector does not work

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#19]
Testset:
cameron.howe

config.php:
'excludes' => [
      'category' => [
       ],
       'group' => ['ORGA'
   ],
],
'conversions' => [
    'vip' => [
         'category' => [
          ],
          'group' => ['VIP'
      ],
],

Result:
Downloading
   53 [============================]
Downloaded 53 vcard(s)
Parsing vcards
Converted 33 vcard(s)

What should be excluded has been included. With two exceptions:
one record is correct ("LEGO") which was also marked as a VIP group.
And "Cameron" wich is marked as PERS, ORGA & VIP group.
That's why I can not detect an error pattern here.

**Comment by MarkusHLudwigsfeld** [comment]
@BlackSenator 
You can try "categories" for the filter instead of "category", e.g. Nextcloud VCARD uses "categories".

**Comment by BlackSenator** [comment]
Hallo Andreas,

check doch noch mal das Coding für Exclude/Include:
1 . Fall
'filters' => [
        'include' => [                       // if empty include all by default
            'categories' => [
            ],
            'group' => [
            ],
        ],
        'exclude' => [
            'categories' => ['Business','Sonstige','UNKNOWN','Volker'
            ],
        ],
Ergebnis: "Converted 0 vcard(s)"

Eigentlich gleiches Setting:
'filters' => [
        'include' => [                       // if empty include all by default
        ],
        'exclude' => [
            'categories' => ['Business','Sonstige','UNKNOWN','Volker'
            ],
        ],
Ergebnis: Converted 433 vcard(s)  -  und das passt schon eher ...

**Comment by andig** [comment]
Im 1. Fall hast Du für include 2 Regeln angegeben, die aber dazu führen dass nix inkludiert wird :O. Wenn musst Du include komplett leer lassen. Vielleicht baue ich da noch eine Warnung ein…

Viele Grüße, Andreas
