### ISSUE TITLE
OpenSSL Error messages:   error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by robkalmeijer** [andig/carddav2fb#190]
[robkalmeijer@server3 ~]$ cd carddav2fb-master/
[robkalmeijer@server3 carddav2fb-master]$ ll
totaal 108
drwxr-xr-x. 2 robkalmeijer users 4096 nov 17 22:38 assets
-rwxr-xr-x. 1 robkalmeijer users  355 nov 17 22:38 carddav2fb
-rw-r--r--. 1 robkalmeijer users  599 nov 17 22:38 composer.json
-rw-r--r--. 1 robkalmeijer users   25 nov 17 22:38 config.cron
-rw-r--r--. 1 robkalmeijer users 3608 nov 17 22:38 config.example.php
-rw-r--r--. 1 robkalmeijer users 3643 jan 14 00:07 config.php
-rwxr-xr-x. 1 robkalmeijer users  705 nov 17 22:38 docker-entrypoint
-rw-r--r--. 1 robkalmeijer users  826 nov 17 22:38 Dockerfile
-rw-r--r--. 1 robkalmeijer users  420 nov 17 22:38 phpstan.neon
-rw-r--r--. 1 robkalmeijer users  227 nov 17 22:38 phpunit.xml
-rw-r--r--. 1 robkalmeijer users 4796 nov 17 22:38 README.md
drwxr-xr-x. 5 robkalmeijer users 4096 nov 17 22:38 src
drwxr-xr-x. 2 robkalmeijer users 4096 nov 17 22:38 tests
[robkalmeijer@server3 carddav2fb-master]$ composer install --no-dev
Loading composer repositories with package information

  [Composer\Downloader\TransportException]
  The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
  Failed to enable crypto
  failed to open stream: operation failed

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by andig** [comment]
Related to composer/packagist, not to carddav. Please retry, maybe upgrade composer.
