### ISSUE TITLE
Adress target phone book(s)

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#2]
It should be possible to address the destination phonebook with number [0..n] and name in the configuration data. According to the issue before: more than one destination phone book could be considered.

**Comment by andig** [comment]
> It should be possible to address the destination phonebook with number [0..n] and name in the configuration data.

Gibts schon: https://github.com/andig/carddav2fb/blob/master/config.example.php#L5

> According to the issue before: more than one destination phone book could be considered.

Anderes Thema, behandeln wir im entsprechenden Issue.
