### ISSUE TITLE
New error occurred - guzzeling and regurgitate

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#20]
I'm totally puzzled!

Nothing changed to issue #19 - no new release downloaded - suddenly this error occured:

volumio@volumio:/carddav2fb$ php carddav2fb.php run
Downloading
    0 [>---------------------------]

  [GuzzleHttp\Exception\ConnectException]
  cURL error 7: Failed to connect to p68-contacts.icloud.com port 443: Connec
  tion refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

run [-i|--image] [-c|--config CONFIG]

**Comment by BlackSenator** [comment]
This is something wrong in the access from my home network to the desired server. I also tried it with the original solution from Jens Maus and also there the https request gives an error!

**Comment by andig** [comment]
Komisch. Browser geht?
