### ISSUE TITLE
docker run => standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by uelpenich** [andig/carddav2fb#202]
Raspberry Pi 3 with Buster
* installated version works
* Docker image doesn't work:
**1st try:**
pi@raspberrypi:~ $ docker run --rm -v ./carddav2fb-config:/data andig/carddav2fb -i
Unable to find image 'andig/carddav2fb:latest' locally
latest: Pulling from andig/carddav2fb
4167d3e14976: Pull complete
bec22c3b8bd7: Pull complete
1e08b345e354: Pull complete
88037c41e6b6: Pull complete
Digest: sha256:60b66542dc2a8dc47f2fd3eb7f0dbd6db1bb885d8715e1781d9964862660dff4
Status: Downloaded newer image for andig/carddav2fb:latest
docker: Error response from daemon: create ./carddav2fb-config: "./carddav2fb-config" includes invalid characters for a local volume name, only "[a-zA-                    Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
pi@raspberrypi:~ $

**2nd try:**
pi@raspberrypi:/home/carddav2fb $ docker run --rm -v carddav2fb-config:/data andig/carddav2fb -i
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by andig** [comment]
Not sure what you mean?

 > If you intended to pass a host directory, use absolute path.

This is obvious. Use an absolute path.

> standard_init_linux.go:211: exec user process caused "exec format error"

This is obvious too. You cannot run an x64 image on a Raspi. We don't offer multi-arch builds yet but you can build your own.

**Comment by uelpenich** [comment]
As a Docker newbe I had appreciated a comment or hint that the docker image is an intel 64 bit image only. I wasted a lot of time to point it out.

>> Use an absolute path.
Sorry, I followed the example:
`docker run --rm -v ./carddav2fb-config:/data andig/carddav2fb command...`

Meanwhile I tried to build my own armv7 image. => The problem is for alpine linux no php-mailer package is available.

**Comment by andig** [comment]
Please open separate isseu for phpmailer- it should not be required.

**Comment by andig** [comment]
I would also appreciate a PR for fixing the example, sorry for giving the wrong guideline there.

**Comment by uelpenich** [comment]
Thank you for the fast image update. 
The docker version of Branch **docker2** is working on a raspberry pi 3 running buster O/S. 
Build your own docker image with:
```
cd carddav2fb
docker build –t carddav2fb .
```
Prepare the config directory **carddav2fb-config** used as docker volume and copy the prepared config.php to it:
```
mkdir carddav2fb-config
cp config.php carddav2fb-config
```
Run your own docker image:
`docker run --rm -v $(pwd)/carddav2fb-config:/data carddav2fb _command_
`
**Question:** 
Does the intended cron configuration work on raspberry buster?
`Copied config.example.cron to /data volume. Please edit and rename to config.cron`
If not then edit **/etc/crontab** to run carddav2fb once every day at 07:03 

```
# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
07   3  *  *  * root      docker run --rm -v /pi/carddav2fb/carddav2fb-config:/data carddav2fb run -i
```
