### ISSUE TITLE
VIPs are not marked in FB as important (Groups)

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#21]
Testset cameron: import all vCards mark important 

config.php:
no filters set
        'conversions' => [
                'vip' => [
                        'category' => [
                        ],
                        'group' => ['VIP'
                        ],
                ],
Result:
- download & upload complete
- only 2 of 4 vCards are marked as expected

**Comment by andig** [comment]
Hab ich mir auch angeschaut. In meinem Testset sind nur 2 Vcards mit group=vip. Damit ist das das erwartete Ergebnis. Wo sind es bei Dir 4?

**Comment by BlackSenator** [comment]
Ich schrieb ja: "no filters set" - also werden alle 50 Kontakte gezogen
VIPs sind
- LEGO,
- St. Olavs,
- Cameron und
- Kathrin Jäger

**Comment by andig** [comment]
Mal in Ruhe: ist der Fehler im Upload oder schon in den runtergeladenen Kontakten? Ich hab leider keine Zeit mir alles selber rauszusuchen :(
