### ISSUE TITLE
VIPs are not marked in FB as important (CATEGORIES)

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#22]
Testset cameron: import all vCards mark important

config.php:
no filters set
'conversions' => [
'vip' => [
'category' => ['VIP'
],
'group' => [
],
],

Result:
- download & upload complete
- none of the 4 vCards are marked as expected

**Comment by BlackSenator** [comment]
I just testet the same setting with the predecessor solution from Jens Maus - there the CATEGORIES in it the CATEGORIES are clearly recognized.
So it's proven that the test data has CATEGORIES that comply with the vCARD standard

**Comment by andig** [comment]
Können wir das auf deutsch machen? Kannst Du mal bitte eine anonymisierte vcard zeigen die das Problem hat?

**Comment by andig** [comment]
Ich habe reingeschaut. In der VCARD sieht das so aus:

    "BEGIN:VCARD
    VERSION:3.0
    X-ADDRESSBOOKSERVER-KIND:group
    PRODID:-\/\/Apple Inc.\/\/iOS 9.3.5\/\/EN
    N:VIP
    FN:VIP
    UID:A25A9915-CFB7-4AC2-AB35-B6310FA8E707
    X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:bla
    X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:bla
    X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:bla
    X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:bla
    END:VCARD
    ",
        
Nach der Umwandlung sieht das so aus:

    "group": "VIP"

Die "CATEGORIES" heißen also einfach "group" und darauf musst Du matchen. Keine Ahnung welchen Standard Du meinst.

Beim testen würde es helfen wenn Du Dir einfach die Zwischenschritte anschaust, dann werden die Zusammenhänge klar.

**Comment by BlackSenator** [comment]
Jetzt verstehe ich nix mehr. Mein Verständnis war:
- was in 'category' => [] steht, wird gegen das vCard-Attribut CATEGORIES verprobt
- was in 'groups' => [] steht, wird gegen aufgelöste Apple-Gruppen verprobt

oder nicht?

Die Testdaten von Cameron haben sowohl gruppiert als auch geichlautend mit CATEGORIES versehen - so dass man die unterschiedlichen Konstellationen der CardDAV-Server testen kann.

**Comment by andig** [comment]
> Mein Verständnis war .. oder nicht?

Jaein. Betonung ist war. Es gibt keine Automatik mehr. Alle Attribute werden 1:1 so überführt wie sie in der Quelle vorhanden sind. Das Appleding heißt group.

Du kannst Dir die vcards im Export anschauen, dann weisst Du was drin ist.
