### ISSUE TITLE
Example for VIP identifications are invalid 

### ISSUE THREAD

**Issue by blacksenator** [andig/carddav2fb#227]
config_example.php shows wrong attribute label: "category" instead of "categories"

**Comment by axelrathey** [comment]
Hi,
ich gehe davon aus, dass die config.example.php dann auch in blacksenators fork dahingehend zu ändern ist. Wobei die alte Einstellung bei mir bisher nicht zu Fehlern führte. Vermutlich weil ich das VIP Filter Feature nicht nutze
Axel

**Comment by blacksenator** [comment]
andigs master is merged into my fork as soon as there is a change in it
