### ISSUE TITLE
+49 replacement in config example

### ISSUE THREAD

**Issue by jsjsjsjs** [andig/carddav2fb#242]
In 'config.example.php' line 105 '+49' is replaced by empty string. 
To make this work correct it should be replaced by '0', not an empty string. 

One could skip this replacement anyway as dialing is working fine with the number starting with '+49'

**Comment by blacksenator** [comment]
@jsjsjsjs
Thank you very much for your hint. `config.example.php` shows examples of a configuration. So you can enter whatever is suitable for you there. The example mentioned may not be suitable for you - but certainly for other users.
What is really an error is the notice: "conversions are processed consecutively. Order decides!" correctly it should read: "conversions are processed length descending!" So the longest strings on the left are processed before the shorter ones. I will correct that.
