### ISSUE TITLE
Integration of profil images

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#3]
Integration of profile pictures incl. download from CardDAV server, caching (FB memory, USB-stick at FB or local cache memory) and upload to FB. Only new or updated images should be loaded.

**Comment by andig** [comment]
iCloud hat leider keine Photos- ich bräuchte ein konkretes Datenbeispiel mit Photos- sowohl auf Seite CardDav als auf Seite der FritzBox.

**Comment by BlackSenator** [comment]
This feature does not work yet

... with this  settings:
	'conversions' => [
		'groupNameToCategory' => [
			'Bekannte' => 'bekannte',

			...

			'Verwandschaft' => 'verwandtschaft',
			'VIP' => 'vip'
		],
		'vipCategories' => [
			'vip'
		],

**Comment by magicsunday** [comment]
Einfach mal eine Instanz von Baikal (http://sabre.io/baikal/) als lokalen Carddav-Server installieren.

**Comment by churchy16** [comment]
Ich wäre auch an den Photos interessiert.
Würde auch gerne mit testen etc.
Evtl. könnte man ja in einem ersten Schritt das Ganze ohne das Thema "Ausschnitte" implementieren und dann sukzessive erweitern...
(vgl. [diese Diskussion auf IP-Phone-Forum](https://www.ip-phone-forum.de/threads/carddav-to-fritzbox-2-0-neue-version-verf%C3%BCgbar.298117/#post-2265854))

**Comment by andig** [comment]
Im Prinzip kein unlösbares Problem:

  - Bilder sauber in den Ablauf der Kommandos mit einbauen (flag oder separates Kommando)
  - Den CURL-Wahnsinn durch sauberen Psr7 Dateiupload ersetzen

Habe nur gerade wenig Zeit. Wer nachhelfen möchte kann das hier oder per PR:

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=51716808)](https://www.bountysource.com/issues/51716808-integration-of-profil-images?utm_source=51716808&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by churchy16** [comment]
>- Den CURL-Wahnsinn durch sauberen Psr7 Dateiupload ersetzen

Ich bin jetzt (noch) kein Kenner von Psr7, aber wie kann man damit ftp(s) Dateiuploads implementieren?
Denn die Bilder kommen in den NAS der FB und auf den kommt man zunächst ja nur (je nach Einstellung) per ftp(s) oder SMB / Windows-Fileshare drauf...
Oder sehe ich das falsch?

**Comment by andig** [comment]
Mit Psr7 gar nicht, aber mit einer passenden http client Bibliothek wie etwa GuzzleHttp.

**Comment by BlackSenator** [comment]
Mission accomplished

**Comment by churchy16** [comment]
Danke Euch!
Bin gerade dabei noch https-URLs für die FB!-Zugriffe sowie den Image-Upload per ftps zu implementieren.
Melde mich dann per PR.
