### ISSUE TITLE
Wie passt man die Formatierung des Namens an?

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#30]
Wie muss realName konfiguriert werden, damit im Telefonbuch der Name wie folgt formatiert wird:
"NACHNAME, PREFIX VORNAME"
Eine testweise Konfiguration:
'realName' => [
			'{lastname}, **{prefix}**, {firstname}',
			'{fullname}',
			'{organization}'
		],
führt nicht zum erwarteten Ergebnis.

**Comment by andig** [comment]
Was heisst das konkret? Welches Konstrukt (aus dem download Schritt) geht rein und was kommt raus?

**Comment by andig** [comment]
Jetzt nochmal. Hast Du das störende Komma einfach mal rausgelöscht? Das ist
ein String der ohnehin hinterher geparsed wird...

2017-12-18 21:20 GMT+01:00 Black Senator <notifications@github.com>:

**Comment by BlackSenator** [comment]
Hallo Andreas,
immer wenn der erste Teil des Muster-String realName über '{lastname}, {firstname}' hinaus erweitert wird - egal, ob mit oder Komma, dann wird {fullname} verwendet. Für die Sortierung der Personennamen ist das blöd, weil in {fullname} ja der Vorname vorne steht.

**Comment by BlackSenator** [comment]
Okay,
jetzt habe ich das Handling dieser Konfiguration verstanden.
Mit der Umstellung/Definition zu/von:
'realName' => [
			'{lastname}, {prefix} {firstname}',
			'{lastname}, {firstname}',
			'{organization}',
			'{fullname}'
		],
kommt das raus, was ich möchte.

**Comment by andig** [comment]
Wie gesagt- es ist einfach ein String, also nur Text.
