### ISSUE TITLE
Sortierung für Telefonnummern

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#32]
Es wäre sinnvoll, wenn die Telefonnummern pro Kontakt in sortierter Reihenfolge in der xml-Datei abgespeichert werden.
Grund: Beim schnellen OK-Klick auf den Namen z.B. im Fritz!Fon C4, wird standardmäßig die erste Nummer aus der Reihe von n Nummern gewählt.
Wünschenswert wäre es in der config.php eine Speicher-Reihenfolge anhand von type festzulegen:
Beispiel
'sortPhone'  => ['home', 'mobile', 'work', 'other'],
die in der converter.php -> private function addPhone() berücksichtigt wird 

Wenn ich es mir recht überlege, dann wäre eine Möglichkeit gleichzeitig auch noch nach Nummern zu sortieren naheliegend:
'sortPhone' => [
'type' => ['home', 'mobile', 'work', 'other'],
'number' => 1, // 0 = unconsidered, 1 = ascending, -1 =descending
],
Reihenfolge: erst nach Type, dann nach Nummer

**Comment by BlackSenator** [comment]
Wenn ich es mir recht überlege, dann wäre eine Möglichkeit gleichzeitig auch noch nach Nummern zu sortieren naheliegend:
'sortPhone' => [
'type' => ['home', 'mobile', 'work', 'other'],
'number' => 1,                                    // 0 = unconsidered, 1 = ascending, -1 =descending
],

**Comment by andig** [comment]
macht Sinn. PR?

**Comment by BlackSenator** [comment]
Noch eine Konkretisierung der Idee:
Wenn die Type-Sortierung ähnlich wie bei "realname" definiert werden könnte, dann könnte damit nicht nur die Reihenfolge festgelegt werden, sondern auch die Nummern nach Typen includiert bzw. excludiert werden:
'sortPhone' => [
'type' => ['{home}', '{mobile}', '{work}', '{other}', '{fax}'],  // oder z.B. nur ['{home}', '{mobile}', '{other}'],
'number' => 1, // 0 = unconsidered, 1 = ascending, -1 =descending
],

**Comment by andig** [comment]
*like*
