### ISSUE TITLE
Exception mit abbruch sinnvoll?

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#36]
Bei mir hatte sich ein unsinniges Geb.-Datum eingeschlichen. Habe ich erst nach Tagen gemerkt, das der Cron-Job gar kein Update geliefert hat. 
Im manuellen Start zeigte sich dann:
"DateTime::__construct(): Failed to parse time string (24.08.20013) at position 10 (3): Unexpected character"
Ist ja soweit okay, aber sinnvoll wäre, wenn
protected function parseBirthday($value)
    {
        return new \DateTime($value);
    }
Nur einen return liefert, wenn DateTime <> false.
Irgendwie steh ich gerade auf dem Schlauch, wie man das elegant in den Einzeiler einbaut.

**Comment by andig** [comment]
Try... catch? Egtl. fände ich den Abbruch aber besser statt heimlich Konflikte zu ignorieren. 

Viele Grüße,
Andreas

**Comment by BlackSenator** [comment]
Ich habe mir den cron-job mit E-Mail-Benachrichtigung eingerichtet
