### ISSUE TITLE
Doku

### ISSUE THREAD

**Issue by magicsunday** [andig/carddav2fb#37]
Bitte die Doku ergänzen, wie man z.B. welche Filter einstellt, so dass man z.B. nur die Einträge mit Telefonnummer exportieren kann.

**Comment by BlackSenator** [comment]
Es werden nur Kontakte mit Rufnummern konvertiert und exportiert.

Die Filter greifen u.a. nur für Kategorien (categories) oder Gruppen (groups)*
* groups gibt es nur bei iCloud

**Comment by BlackSenator** [comment]
Andreas,
ich denke, das kannst Du schließen
