### ISSUE TITLE
Exclude groups of contacts from upload

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#4]
It should be possible to exclude groups of contacts with the attribute CATEGORIES from converting and / or uploading.
For iOS, it should be possible to map via configuration alternatively groups as categories in order to use this feature.

**Comment by andig** [comment]
> It should be possible to exclude groups of contacts with the attribute CATEGORIES from converting and / or uploading.

Woran sollen Gruppen erkannt werden?

> For iOS, it should be possible to map via configuration alternatively groups as categories in order to use this feature.

Wieder ein separates Thema, aber verstanden.

**Comment by andig** [comment]
Erster Teil via 882c3f07333091a9aaf6b1a6b11921e8b828b805 implementiert

**Comment by andig** [comment]
> It should be possible to exclude groups of contacts with the attribute CATEGORIES from converting and / or uploading.

Via 4f812525e5e4ae8a986493da6252e67f6a5a7c38 implementiert.
