### ISSUE TITLE
Mark important contacts (VIP)

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#5]
The Fritzbox allows phonebook to mark entries as "important". It should be possible to define a category or group the related will receive this mark in the conversion.

**Comment by andig** [comment]
Analog https://github.com/andig/carddav2fb/issues/4: woran werden Gruppen erkannt?

**Comment by andig** [comment]
Habs gefunden:

    <category>1</category>

ist ein VIP.

**Comment by andig** [comment]
Closed via af1af53e2b5a2952ea5c771bc525dc75fc05949e
