### ISSUE TITLE
Upload / Login schlägt fehl

### ISSUE THREAD

**Issue by HerrGuhr** [andig/carddav2fb#51]
Moin!
bekomme folgende Meldung
Fritz!Box 7590 mit FRITZ!OS: 06.93-49653 BETA
================================
Converted 2 vcard(s)
Uploading

In Api.php line 241:
                                                 
  ERROR: Login failed with an unknown response.  
                                                 

================================

Benutzer existiert natürlich, kann sich einloggen usw

**Comment by andig** [comment]
Könntest Du in die 234 bitte mal ein 

    var_dump($output); 

einbauen?

**Comment by HerrGuhr** [comment]
string(165) "<?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>7d697de2</Challenge><BlockTime>8</BlockTime><Rights></Rights></SessionInfo>

**Comment by andig** [comment]
Sehr seltsam. Das ist ein erfolgreicher Login. Und trotzdem bekommst Du die Fehlermeldung?

Viele Grüße,
Andreas

**Comment by andig** [comment]
~~Sehr seltsam. Das ist ein erfolgreicher Login. Und trotzdem bekommst Du die Fehlermeldung?~~

Kommando zurück. SID=000000000 heisst Login fehlgeschlagen. Entweder fehlen Deinem User die Rechte oder Username/Passwort sind falsch.

> Benutzer existiert natürlich, kann sich einloggen usw

Was meinst Du damit? Über die Fritzbox Web UI? Per API kommt er offensichtlich nicht rein, die Fritzbox URL stimmt aber da eine gültige Antwort kommt, nur eben kein Login.

**Comment by HerrGuhr** [comment]
> Entweder fehlen Deinem User die Rechte oder Username/Passwort sind falsch.
Hat alle rechte und Name/PW sind schon richtig - habe selbst die trivialsten passwörter ausprobiert.

> Was meinst Du damit? Über die Fritzbox Web UI? 
Jupp

**Comment by andig** [comment]
Dann kann ich leider nicht helfen. Du kannst das Login direkt mit fritzapi und einem kleinen Skript ausprobieren- solange das nicht geht brauchen wir hier nicht weiter zu suchen :(

**Comment by andig** [comment]
fritzapi siehe https://github.com/andig/fritzapi

**Comment by HerrGuhr** [comment]
Kein problem, wenn du mir sagst wie ;)
Bin kein PHP-Coder

**Comment by BlackSenator** [comment]
Versuch ´mal, ob ein Login mit folgenden credentials funktioniert:
USER: dslf-config
PW: [DeinLoginPasswort]

**Comment by andig** [comment]
Issue mangels Feedback geschlossen.
