### ISSUE TITLE
Hardkodierte fritzbox-url 

### ISSUE THREAD

**Issue by HerrGuhr** [andig/carddav2fb#52]
Die Adresse ist Hardcodiert in der api.php
Datei:
/carddav2fb_andi/src/FritzBox/Api.php
Zeile 26

**Comment by andig** [comment]
Wie kommst Du darauf? Das ist nur ein Default Parameter? Aufgerufen wird es so:

    $fritz = new Api($url, $user, $password, 1);

**Comment by HerrGuhr** [comment]
public function __construct($url = 'fritz.box', $user_name = false, $password = false, $force_local_login = false)

**Comment by HerrGuhr** [comment]
https://github.com/andig/carddav2fb/blob/756f49e5b49b9b882db8df34afc671ed00c7c891/src/FritzBox/Api.php#L26

Das problem ist wenn du z.B. kein DNS hast oder die fb einen anderen namen hat :) 👍

**Comment by andig** [comment]
Wie gesagt, die Zeile ist völlig in Ordnung. Wenn Du ein konkretes Problem hast bitte neues Issue aufmachen. 

Viele Grüße,
Andreas
