### ISSUE TITLE
Fatal Error beim Upload

### ISSUE THREAD

**Issue by GomaTerzuTheSecond** [andig/carddav2fb#53]
Hallo, erstmal großes Danke für deine Mühe, so etwas bereitzustellen. Nachdem ich es an "Laie" geschafft habe den composer auch endlich auf win10 zum Laufen zu bringen und alles zu installieren, bekomme ich nun diesen Fehler, sobald der download und der convert durch sind. Kannst du mir bitte helfen und sagen woran es liegen könnte? Ich habe die XXX als Schwärzung der Zugangsdaten benutzt

edit. Es handelt sich um eine Fritzbox 7490 mit neuester firmware

Uploading
PHP Fatal error:  Uncaught Error: Call to undefined function Andig\FritzBox\curl_init() in C:\carddav\src\FritzBox\Api.php:70
Stack trace:
#0 C:\carddav\src\functions.php(316): Andig\FritzBox\Api->doPostFile(Array, Array)
#1 C:\carddav\src\RunCommand.php(80): Andig\upload('<?xml version="...', 'http://fritz.bo...', 'XXXXXX', 'XXXXXXXX', 0)
#2 C:\carddav\vendor\symfony\console\Command\Command.php(251): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\carddav\vendor\symfony\console\Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\carddav\vendor\symfony\console\Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\carddav\vendor\symfony\console\Applicat in C:\carddav\src\FritzBox\Api.php on line 70

**Comment by andig** [comment]
Du hast anscheinend kein Curl. Frag mich bitte nicht wie das unter Windows geht- evtl. mit Cygwin?

**Comment by GomaTerzuTheSecond** [comment]
Moin, danke für die Rückmeldung. Habe mir curl nach einer Anleitung von Giga installiert und es lässt sich auch über die cmd sofort mit dem curl Befehl aufrufen, aber der identische Error kommt dennoch. Hast du eine weitere Idee, wie man dem beikommen könnte oder weitere Infos, die ich dazuliefern könnte?

**Comment by GomaTerzuTheSecond** [comment]
Ich konnte das Problem selbst lösen. Ich musste in der php.ini noch beim punkt curl_init das Semikolon davor wegnehmen und in der selben php.ini bei curl.cainfo den Pfad zum Zertifikat in Anführungszeichen angeben. Das Zertifikat habe ich in einem beliebigen Ordner abgelegt. Bekommen hab ich das Zertifikat hier http://curl.haxx.se/ca/cacert.pem
