### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by ger82** [andig/carddav2fb#54]
Ich erhalte folgende Fehlermeldung:
````
Downloading vCard(s) from account aaa
    0 [>---------------------------]
In RequestException.php line 113:

  Client error: `PROPFIND http://192.168.178.32/baikal/html/card.php/addressb
  ooks/aaa/default/` resulted in a `401 Unauthorized` response:
  <?xml version="1.0" encoding="utf-8"?>
  <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
    <s:sabredav-version>3 (truncated...)
````
Wenn ich im Browser den Link aufrufe, bekomme ich an der Stelle eine Frage nach Benutzernamen und Passwort. Nach Eingabe dieser erhalte ich dann zugriff auf die vcf's.

Woran kann es liegen das es hier scheitert?

**Comment by spandi** [comment]
Habe genau das selbe Problem. Was das Problem bei dir?

**Comment by spandi** [comment]
Die Ursache ist folgende: Baikal/Sabredav unterstützt digest access authentication, was von carddav2fb nicht unterstützt wird und zum HTTP Error Code 401 führt. Siehe https://github.com/sabre-io/Baikal/issues/68
Workaround: Baikal umstellen auf Basic-Auth via Baikal GUI. Achtung: Sollte nur gemacht werden, wenn der Server SSL verwendet, da das Passwort im Klartext übermittelt wird. Werde ein separates Issue eröffnen für digest access authentication support in carddav2fb
