### ISSUE TITLE
Bilder werden in falsches Verzeichnis geladen

### ISSUE THREAD

**Issue by caldir65** [andig/carddav2fb#66]

**Comment by caldir65** [comment]
die Bilder werden wohl extrahiert und hochgeladen, sie landen jedoch offenbar im root des FTP-Servers der FB - im Tel-Buch wird aber der Pfad eingetragen, der auch in der Config.php steht. Natürlich werden so die Bilder dann nicht gefunden ... 

Beim Upload bekomme ich ausserdem Meldungen wie folg:

Detaching and uploading image(s)
PHP Notice:  Undefined index: fonpix in /home/carddav2fb/carddav2fb.2.master/src/functions.php on line 65
[... wiederholt sich insges. 18 Mal...]
Uploaded 18 image file(s)
Converted 44 vCard(s)
Uploading
Successful uploaded new Fritz!Box phonebook

Den Pfad zum Zielordner der Bilder habe ich mir wie unter https://www.ip-phone-forum.de/threads/carddav2fb-neue-version-image-upload-verf%C3%BCgbar.301897/ beschrieben aus dem FB-Addressbuch ausgelesen.

Btw. wenn ich in der Config einen anderen Zielpfad angebe, so wird dieser auch im Telbuch eingetragen - könnte man damit nicht ein beliebige Verzeichnis auf dem NAS/ftp mit den Bildern füttern, vorzugsweise auf einem externen Laufwerk, um den internen Speicher der Box nicht über gebühr zu strapazieren?

Gruß, Christoph

**Comment by BlackSenator** [comment]
Ich habe Dir im ip-phone-forum geantwortet.

**Comment by andig** [comment]
> PHP Notice: Undefined index: fonpix in /home/carddav2fb/carddav2fb.2.master/src/functions.php on line 65

@BlackSenator magst Du das fixen? Einfach vorher abfragen ob der Index (und ähnliche Stellen) existiert.

**Comment by BlackSenator** [comment]
Ich kümmere mich schon
