### ISSUE TITLE
";" apears sometimes at the end of names

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#7]
In some cases a ";" apears at the end of the name in the phonebook.
It only affects companies, so if no first name or last name is included. But not all company contacts. There is no pattern recognizable.

**Comment by andig** [comment]
Could you please show the vcard that creates the problem (cpuidle@gmx.de)

**Comment by andig** [comment]
Ich mach's zu bis ich ein Beispiel habe.
