### ISSUE TITLE
Get rid of fritzbox\Api

### ISSUE THREAD

**Issue by andig** [andig/carddav2fb#78]
Its only remaining use is POSTing the phonebook- that can be replaced by a guzzle call.

**Comment by andig** [comment]
It should be enough to do something like this:

    // Create the request.
    $request = $client->createRequest("POST", "http://example.com/image/add");

    // Set the POST information.

    $postBody = $request->getBody();
    $postBody->setField('user_id', $userId);
    $postBody->setField('api_key', $token);
    $postBody->setField('product_id', $product_id);
    $postBody->addFile(new PostFile('image[data]', fopen('tmp/images/'.$input->image, 'r')));

    // Send the request and get the response.
    $response = $client->send($request);

@blacksenator: would you be interested in tackling this?

**Comment by BlackSenator** [comment]
Bin dabei ...

**Comment by BlackSenator** [comment]
Hmm...
ich stehe auf´m Schlauch - irgendwie komme ich über die Zuweisung des Clients nicht hinaus:
`$client = new \GuzzleHttp\Client(['base_url' => $fritzbox['url']]);`
beim Request scheitere ich schon - ich weiß noch nicht was der zweite Parameter sein muss.
`$request = $client->createRequest("POST", ???);`

**Comment by andig** [comment]
Du musst vmtl nur das Beipiel von oben mit dem aktuellen code aus api abgleichen, dazu in gie guzzle doku schauen. Was fehlt Dir komkret?

**Comment by andig** [comment]
Z.B. Hier https://github.com/andig/carddav2fb/blob/master/src/FritzBox/Api.php#L76 die url.

**Comment by BlackSenator** [comment]
`$postBody->setField('user_id',` `$fritzbox['user']);`
setfield führt zu
`Uncaught Error: Call to undefined method GuzzleHttp\Psr7\Stream::setField()`
Das findet sich auch in diversen (älteren) Posts - leider keine Lösung welche Routine anstelle dessen benutzt werden soll, um die Werte zu setzen

**Comment by BlackSenator** [comment]
wie hast Du das so schnell gefunden? Ich wühle mich seit einem Tag durch die Doku, GitHub, Google und stackoverflow :(

**Comment by andig** [comment]
Einfach in der Guzzle Doku nach File gesucht?

Viele Grüße,
Andreas

**Comment by derwok** [comment]
Hi,
I just stumbeld upon this issue here...
My question is: why do we want to get rid of the Fritz API and "roll our own"? When AVM changes the way to access the Fritz Box (URL, authentication, ...), we always have to keep our stuff up to date. And the Fritz API code itself seems to work quite stable and was well tested in the past years...
@andig could you give some background?

**Comment by andig** [comment]
Because the hand-crafted curl code is cumbersome and hard to maintain. Guzzle is a well-maintained alternative. Also, we already *have* replaced *all* of it except the file upload which really isn‘t fritz api but a simple http post.

**Comment by BlackSenator** [comment]
I also thought about a change to the TR-064 Interface - according to AVMs policies to gate lock the firmware.
I’ve already successful tested their new contact upload (see my fbcallrouter repo).
The only obstacle is, that their is no full upload available yet(!)*:
So first you’ve to delete the phone book, than implement an new (empty) one and than upload each single contact.
Positive: here is room for improvements  via the (FB) unique ID - e.g. manipulations only on designated contacts ...
Negative: a new (short) library for the class of SOAP routines will be necessary

**Comment by andig** [comment]
> I also thought about a change to the TR-064 Interface - according to AVMs policies to gate lock the firmware.

May be possible, haven't checked. Different topic though ;)

**Comment by andig** [comment]
Because the scope of this ticket is

> Its only remaining use is POSTing the phonebook- that can be replaced by a **guzzle call**.

**Comment by BlackSenator** [comment]
Ich komme mit dem Thema nicht voran.

**Comment by andig** [comment]
Ok, ich habs mal ins Blaue runtergeschrieben, ungetestet. Statt `doPostFile` könnte das so aussehen, setzt natürlich (für die SID) eine initialisierte FB-Verbindung voraus:


    function postFile(array $formfields, array $filefields) {
        $multipart = [];

        // sid must be first parameter
        $formfields = array_merge(array('sid' => $this->sid), $formfields);

        foreach ($formfields as $key => $val) {
            $multipart[] = [
                'name' => $key,
                'contents' => $val,
            ];
        }

        foreach ($fileFields as $name => $file) {
            $multipart[] = [
                'name' => $name,
                'filename' => $file['filename'],
                'contents' => $file['content'],
                'headers' => [
                    'Content-Type' => $file['type'],
                ],
            ];

        }

        $url = $this->url . '/cgi-bin/firmwarecfg';
        $resp = $client->request('POST', $url, [
            'multipart' => $multipart,
        ]);
    }

Aufruf mit den gleichen Parametern wie heute auch. Magst Du's nochmal versuchen?

**Comment by andig** [comment]
Siehe https://github.com/andig/carddav2fb/pull/96. 

Müsste jetzt noch getestet werden und eine Möglichkeit gefunden um zusätzliche HTTP Client Optionen wie `"verify" => false` aus der Config mit zur Fritzbox als auch zum Backend zu geben um #64 zu lösen.
