### ISSUE TITLE
Counter does not count

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#8]
Thanks for implementing the interaction messages about retrieving, converting and upload.

But the download counter seems stucking ...
Downloaded 0 vcards
Converted 610 vcards
Uploaded fritz phonebook

The amount of converted cards is correct. I´ve 1398 contacts and excluded two groups (categories) with together 788 contacts

**Comment by andig** [comment]
Fixed bbafac4127e912f0631c6050c17ae40dd1c158c9
