### ISSUE TITLE
Image upload failed

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#82]
` Call to undefined function Andig\ftp_connect() in C:\Users\Admin\Documents\Development\Sandbox\carddav2fb\src\functions.php:58`
So implemented a new setting for test in my sandbox fresh form the field (from upstream master):
Same result!
I´m just a little bit puzzled why this suddenly fails? It´s probably easy, but I´m too tiered to trace the bug :(

**Comment by andig** [comment]
Does it work when prefixed with \?

**Comment by derwok** [comment]
Can you check your PHP installation as described here:
https://stackoverflow.com/questions/18467876/ftp-connect-fatal-error-call-undefined-function

**Comment by BlackSenator** [comment]
Ich war gerade unterwegs - unmittelbar vorher war ich in der selben Richtung gedanklich auf der Spur.
Auf dem RasbPi läufts nämlich und in php.net steht, das ftp für 7.x unter Windows das explizit enebled werden muss.
Teste ich gleich.
Was mich wundert, ist die Tatsache, dass ich vorher definitiv den Image Upload unter Win testen konnte...

**Comment by BlackSenator** [comment]
Solved:

https://secure.php.net/manual/de/ftp.installation.php

> ..., as of PHP 7, to enable this on Windows you have to add the line:
extension=php_ftp.dll
to your php.ini to resolve PHP errors that tell you PHP FTP functions are not defined; **the line isn't in there (where, many things are and are just commented out).**

**Comment by andig** [comment]
Wouldn't it be nice to implement a quick function_exists() check before the user runs into unclear error message?

**Comment by derwok** [comment]
Good idea to check and die gracefully.
As I introduced the ftp_* stuff, I can take care for that.
Please re-open this issue.
