### ISSUE TITLE
Image upload geht nicht wenn der Ordner leer ist - ftp_nlist bug

### ISSUE THREAD

**Issue by Falseee** [andig/carddav2fb#87]
Habe gerade carddav2fb bei mir auf einem PI eingerichtet und die Kontakte wurden auch erfolgreich synchronisiert, allerdings konnten die Bilder nicht hochgeladen werden.
Habe mich jetzt durch den code gewühlt und folgende Stelle gefunden
https://github.com/andig/carddav2fb/blob/master/src/functions.php#L64-L85

Habe mir also den Abschnitt kopiert und local in der IDE mal ausgeführt und rumgetestet...
Nach etwas suchen bei google habe ich gelesen das ftp_nlist false zurückgibt wenn der Ordner leer ist.

Lösungsansatz:
Man könnte mittels ftp_rawlist prüfen ob dieser leer ist, da diese funktion ein leeres Array zurück gibt wenn keine Datein vorhanden sind (so wie es bei ftp_nlist eigentlich auch sein sollte).

**Comment by derwok** [comment]
Interessant!
Schaue ich mir an!
Danke für die genaue Analyse!
