### ISSUE TITLE
VIP with gaps

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#9]
Thanks for fixing the issue regarding to 'groupNameToCategory' and 'vipCategories'.

All VIPs are correct marked as "important" in the FB phonebook - but with a funny gap: all VIPs from one Group (category) slipped through the cracks. I´m still testing the possible reasons. Just one idea: It may be the sequenze (position) of the VIP-attribute in the CATEGORIES Array?

**Comment by andig** [comment]
> It may be the sequenze (position) of the VIP-attribute in the CATEGORIES Array?

Yes. The first matched group will be the category.

As asked before: does the group to category mapping make any sense or can it be removed? Wouldn't it be sufficient to have:

  - groups to skip and
  - groups to mark as vip

categories is an implementation detail of the old solution that imho doesn't make sense.

Opinions?

**Comment by BlackSenator** [comment]
It makes sense to use the attribute CATEGORIES for making the selection of to be acquired or to be skipped contacts, because this is the only meaningful vCard attribut for this porpuse.
Apple contacts do not provide the CATEGORIES attribute - but use a similar data: groups. For me these are just two terms of different (for Apple proprietary) standards.

Considering this, the following results for me as controls in config.php:

1. A flag (boolean) whether for Apple vCards the GROUPS should be converted into CATEGORIES. If true, all groups will be resolved and the names of the groups (1..n) will be written in the CATEGORIES field of the contacts (example: >CATEGORIES:'Family','VIP'< or >CATEGORIES:'VIP','relatives'<). This would then correspond to what is provided by other CardDAV servers and can then be treated similarly (see 2./3.).
So from my pos it does not make sense using a mapping table which group should become which category. A plain 1:1 transfer is logical right when flag is true.  
 
2. Definition of CATEGORIES (1..n) which should explicit not be uploaded to FB. To give the user more flexibility this could be combined in addition with an boolean flag if this configuration of categories should excluded (default) or included.

3. Definition of the CATEGORIES (1..n) with which the contacts are marked, which should receive the characteristic "important" in the FB.

**Comment by andig** [comment]
> It makes sense to use the attribute CATEGORIES for making the selection of to be acquired or to be skipped contacts, because this is the only meaningful vCard attribut for this porpuse.
Apple contacts do not provide the CATEGORIES attribute - but use a similar data: groups. For me these are just two terms of different (for Apple proprietary) standards.

Ok. Aber dann können wir auch einfach Folgendes machen:

	{
		"exclude: {
			"category": [
				"a", "b"
			],
			"group": [
				"c", "d"
			],
		},
		"vip: {
			"category": [
				"vip1"
			],
			"group": [
				"vip2"
			],
		}
	}

Es macht keinen Sinn zwischendurch vcard <-> vcard zu mappen

**Comment by andig** [comment]
Siehe f18728651d974cc0360f5fc8cf264b2a6c07cfeb. Wenn eine vcard "groups" hat kann man diese zum filtern oder für vip nehmen, wenn es "categories" sind auch die. Sollte jetzt alles flexibel sein.

Es gibt kein group->category Mapping mehr.
