### ISSUE TITLE
Image upload instable

### ISSUE THREAD

**Issue by BlackSenator** [andig/carddav2fb#94]
Downloaded 1728 vCard(s)
Dissolving groups (e.g. iCloud)
Dissolved 18 group(s)
Filtering 1710 vCard(s)
Filtered out 1278 vCard(s)
Detaching and uploading image(s)
   0/432 [>---------------------------]   0%PHP Warning:  ftp_login(): Access to home directory from internet not allowed. in C:\Users\Admin\Documents\Development\Git\carddav2fb\src\functions.php on line 73

Warning: ftp_login(): Access to home directory from internet not allowed. in C:\Users\Admin\Documents\Development\Git\carddav2fb\src\functions.php on line 73

ERROR: Could not log in tr_064user to ftp server fritz.box for image upload.
 432/432 [============================] 100%
Converted 432 vCard(s)
Uploading
Successful uploaded new Fritz!Box phonebook

config data:
    'fritzbox' => [
        'url'      => 'http://fritz.box',
        'user'     => 'tr_064user',
        'password' => 'xxxxxxxxx',
        'fonpix'   => '/FRITZSTICK/FRITZ/fonpix',
    ],

    'phonebook' => [
        'id'           => 0, 
        'name'         => 'Telefonbuch',
        'imagepath'    => 'file:///var/InternerSpeicher/FRITZSTICK/FRITZ/fonpix/',
    ],

**Comment by derwok** [comment]
Vielleicht was mit deinen Rechten?
Siehe zb hier. 
https://www.ip-phone-forum.de/threads/berechtiungsproblem-nach-update-auf-version-7-01-bei-der-7490.300853/#post-2296064

**Comment by derwok** [comment]
Hab zu spät gesehen, dass BlackSenator schon einen PR bereit hat.

@BlackSenator: Wenn der PR im Text "Fixes #94" stehen hat, dann wird der PR auch hier beim Issue angezeigt. Dann sieht man das sofort.

**Comment by BlackSenator** [comment]
Na, das sind die credentials mit denen ich unverändert seit Anfang an teste...

Volker Püschel
Am Wolfshagen 4
30974 Wennigsen
T +49-5045-911-484
M +49-177-7960362
F +49-5045-911-500 volker.pueschel@anasco.de

**Comment by BlackSenator** [comment]
Hmmmm,
gleicher User gleiche Rechte (wie schon seit Monaten) - eben noch ´mal ein Test auf dem RasbPi: läuft! (Errors gestern waren von den Tests auf meiner Development Umgebung / Sandbox unter Win10)
Ich benutze den Image Upload eh nicht in der Praxis (teste nur die Releases)

**Comment by andig** [comment]
Kann es sein dass Deine Windowskiste in einem anderen Netzwerk hängt und damit

> Warning: ftp_login(): Access to home directory from internet not allowed. in 

für die FB aus dem Internet kommt? So stehts jedenfalls eindeutig in der Fehlermeldung?
